name: Create Release

on:
  push:
    tags:
      - 'v*'  # Triggers on versions following the pattern vX.X.X

jobs:
  release:
    name: Create and Upload Release
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step to find and rename the 'kubectl' file (the version embedded file)
      - name: Find and rename kubectl file
        id: find_kubectl
        run: |
          KUBECTL_FILE=$(find kubectl -name "kubectl_v*_amd64")
          if [ -z "$KUBECTL_FILE" ]; then
            echo "kubectl file not found!"
            exit 1
          fi
          echo "KUBECTL_FILE=$KUBECTL_FILE" >> $GITHUB_ENV
          echo "Found kubectl file: $KUBECTL_FILE"
          
      # Copy files and list directory to confirm contents
      - name: Prepare release files
        run: |
          mkdir -p release
          cp kubectx/kubectx ./release/kubectx
          cp kubectx/kubens ./release/kubens
          cp "$KUBECTL_FILE" ./release/kubectl
          
      - name: List release directory contents
        run: ls -l release

      # Create tar.gz of selected files
      - name: Create tar.gz of selected files
        run: |
          tar -czvf release/my-release.tar.gz -C release kubectx kubens kubectl
      
      - name: Get version from tag
        id: extract_tag
        run: echo "::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}"

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.extract_tag.outputs.VERSION }}
          release_name: Release ${{ steps.extract_tag.outputs.VERSION }}
          draft: false
          prerelease: false

      - name: Upload tarball to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/my-release.tar.gz
          asset_name: my-release.tar.gz
          asset_content_type: application/gzip
